### ISSUE TITLE
Add `chain` level in connector `contractAddresses` lookup

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#5619]
**Feature Suggestion**

Currently `contractAddresses` in each DEX connector template only supports various networks - for example, see https://github.com/hummingbot/hummingbot/blob/master/gateway/src/templates/uniswap.yml. Since Uniswap and other DEXs live on different networks on different chains, it would be better to add a `chain` level so that the config template can define addresses for each network on different chains with the format:

```
contractAddresses:
  ethereum:
    mainnet:
    kovan:
  polygon:
    mainnet:
    mumbai:
```

The controller file for each DEX must be modified to handle this change.

**Impact**

Prevents collisions in network name. Currently, the only reason that Uniswap works is that the `mainnet` address is identical for their Polygon and Ethereum deployments.

**Additional context**
