### ISSUE TITLE
Documentation of the configuration params for the GridStrike controller is incomplete

### ISSUE THREAD

**Issue by dbutti** [hummingbot/hummingbot#7418]
Hello, please excuse if my questions are naive...

I am having a quite hard time trying to figure out exactly how the several parameters to the grid_strike controller interact to determine how the grids are setup. Also, I had no luck activating the debug log option which (according to the source code) should dump detailed information into the logs when the grids are computed.

Would it is possible to get some fully commented example, in order to better understand which parameters are optional, and how they interact if they are in conflict? It would be helpful as well to see how the stop loss/take profit options should be entered.

Thank-you

**Comment by rapcmia** [comment]
When testing controller or connector updates, always use this template then adjust depends on diff use cases
```
leverage: 10              # Futures leverage multiplier (10x buying power).
position_mode: HEDGE      # HEDGE=long+short can coexist; ONE_WAY=one direction only.
connector_name: binance
trading_pair: BTC-FDUSD
side: 1                          # Trade direction: 1=BUY, 2=SELL.
start_price: '1.4'               # Lower price boundary of the grid.
end_price: '1.428'               # Upper price boundary of the grid.
limit_price: '1.393'             # Safety floor (BUY) or ceiling (SELL); executor stops if breached.
min_spread_between_orders: '0.0003' # Minimum % gap between grid levels (0.03%).
min_order_amount_quote: '12'     # Minimum order size in quote currency.
max_open_orders: 4               # Max concurrent active grid orders.
max_orders_per_batch: 1          # Orders placed per cycle; controls entry pace.
order_frequency: 5               # Seconds between each strategy cycle.
activation_bounds: 0.003         # Only place orders within 0.3% of current price; avoids stale fills.
keep_position: false             # On stop: false=close positions, true=leave them open.
triple_barrier_config:
  open_order_type: 3             # Entry order type: 1=MARKET, 2=LIMIT, 3=LIMIT_MAKER (post-only).
  stop_loss: null                # Per-order stop-loss disabled; limit_price is the safety net.
  stop_loss_order_type: 1        # Stop-loss order type: 1=MARKET, 2=LIMIT, 3=LIMIT_MAKER.
  take_profit: '0.0002'          # Per-order profit target (0.02% above entry).
  take_profit_order_type: 1      # Take-profit order type: 1=MARKET, 2=LIMIT, 3=LIMIT_MAKER.
  time_limit: null               # No time-based expiry on positions.
  time_limit_order_type: 1       # Time-limit exit order type: 1=MARKET, 2=LIMIT, 3=LIMIT_MAKER.
  trailing_stop: null            # Trailing stop disabled.
```
- You may want to start with the start, end and limit prices
- limit prices depends on the side you set (BUY or SELL)
- your desired number of active orders and how the controller places orders as well
